spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ceramics_pipeline?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Theanh@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
      hibernate.jdbc.lob.non_contextual_creation: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

cloudinary:
  url: cloudinary://632641588972872:O1Ik4PlUtr5WZ6-1g6x_xbuLYdU@dwzjxsdli

logging:
  level:
    root: INFO
    org.springframework.data.repository: DEBUG

